spring:
  config:
    activate:
      on-profile: local
  application:
    name: pickle
  datasource:
    url: jdbc:mysql://localhost:3306/dnd
    username: dnd
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: my-local-bucket-name

jwt:
  secret-key: test+test+test+test+test+test+test+test+test+test

oauth:
  oidc:
    google:
      issuer: "https://accounts.google.com"
      audience: google-local-client-id
      jwks-uri: "https://www.googleapis.com/oauth2/v3/certs"
    kakao:
      issuer: "https://kauth.kakao.com"
      audience: kakao-local-client-id
      jwks-uri: "https://kauth.kakao.com/.well-known/jwks.json"

springdoc:
  swagger-ui:
    url: /api-docs/openapi3.yaml
    disable-swagger-default-url: true
