spring:
  config:
    activate:
      on-profile: local
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/dnd
    username: dnd
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret-key: test+test+test+test+test+test+test+test+test+test

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
  oidc:
    google:
      issuer: "https://accounts.google.com"
      audience: ${oauth.google.client-id}
      jwks-uri: "https://www.googleapis.com/oauth2/v3/certs"
    kakao:
      issuer: "https://kauth.kakao.com"
      audience: ${oauth.kakao.client-id}
      jwks-uri: "https://kauth.kakao.com/.well-known/jwks.json"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    url: /swagger-ui/openapi3.yaml
    enabled: true
    path: /swagger-ui/index.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
  enable-spring-security: false